#pragma once

#define FLOATNOTE_VERSION_MAJOR 1
#define FLOATNOTE_VERSION_MINOR 0
#define FLOATNOTE_VERSION_PATCH 0
#define FLOATNOTE_VERSION_BUILD 0

#define FLOATNOTE_VERSION_TUPLE 1, 0, 0, 0
#define FLOATNOTE_VERSION_STRING "1.0.0"
#define FLOATNOTE_FILE_VERSION_STRING "1.0.0.0\0"
#define FLOATNOTE_VERSION_WSTRING L"1.0.0"
